name: Build wheel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync --locked --all-extras --dev
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: hostsctl-wheel
          path: dist/*.whl
